language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install beautifulsoup4 lxml requests coverage coveralls 

script:
  - coverage run tests.py

after_success:
  - coveralls
